### ISSUE TITLE
Add New Folder / Upload Image not working

### ISSUE THREAD

**Issue by louisjrdev** [pruvious/pruvious#35] opened 2024-06-19 17:48 UTC
These buttons are not working, literally nothing, no errors in the console, just a no-op. Same issue happens if I have an image field in my block, I can't upload an image there either.

![CleanShot 2024-06-19 at 18 47 22@2x](https://github.com/pruvious/pruvious/assets/17555062/f4d5c893-1eca-4416-82c9-dd07c0a18eb8)

This only happens if I am using nuxt@3.12.x, if I downgrade to nuxt@3.11.x this issue is resolved

**Comment by murisceman** [comment] 2024-06-19 18:38
Can you provide more information about your environment, operating system, and browser? Also, does this issue only occur in development mode?

**Comment by louisjrdev** [comment] 2024-06-19 18:49
Yes i'm running node 20.11.0, on MacOS, and Chromium (also tested Safari). Yes the issue was occurring in development mode. 

Swapping between nuxt 3.11.x and 3.12.x reliably triggers the issue (working on 3.11.x and not working on 3.12.x)

**Comment by murisceman** [comment] 2024-06-19 18:57
Hmm, I cannot reproduce the issue. I just tried it out with Nuxt `3.12.0`, `3.12.1`, and `3.12.2`, and it works on my Chrome on macOS. It also works fine in Safari.

I tried on a blank installation with `npx pruvious init` and used these dependencies:

```json
"dependencies": {
  "nuxt": "^3.12.2",
  "pruvious": "^3.11.8",
  "vue": "^3.4.29",
  "vue-router": "^4.3.0"
}
```

Do you use any other Nuxt modules besides Pruvious in your project?

**Comment by louisjrdev** [comment] 2024-06-19 19:07
I double checked and I get the behaviour with these versions: 
![CleanShot 2024-06-19 at 20 06 05@2x](https://github.com/pruvious/pruvious/assets/17555062/d165feea-c538-4d95-9c54-07a8dea1b0c0)

I am only using one other module my nuxt.config.ts looks like this: 
```typescript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
	app: {
		head: {
			title: 'Nuxt',
		},
	},

	devtools: {
		enabled: true,
	},

	modules: ['@nuxtjs/tailwindcss', 'pruvious'],

	pruvious: {
		jwt: {
			secretKey: ''// omitted,
		},
	},
});

```

**Comment by louisjrdev** [comment] 2024-06-19 19:12
Also I get the same behaviour in a fresh pruvious project initialised with `pnpm dlx pruvious@latest init <dir>` if I upgrade the nuxt version to `3.12.1`

**Comment by louisjrdev** [comment] 2024-06-19 19:27
Here is a reproduction: https://codesandbox.io/p/devbox/autumn-shape-h6m5jy

**Comment by murisceman** [comment] 2024-06-19 19:33
Thanks for the info, I was able to reproduce the bug on my end after all. I'm not sure what causes it, but it seems to be fixed with Nuxt `v3.12.2`. Can you try to upgrade?

**Comment by louisjrdev** [comment] 2024-06-19 19:42
Yes it works on version `3.12.2` for me, thanks for solving that, must be a regression on nuxt's end that they have already fixed

**Closed** 2024-06-19 19:54 UTC

**Comment by andreasvirkus** [comment] 2024-07-30 20:26
Sorry to resurface this, but I think I'm running into the same issue with `3.12.2`

I'm following along with the tutorial and I'm at the Portfolio block step, this is what I see when I try to add a `New block > Portfolio > Add item > Select from media library`

@louisjrdev was the gallery faded out for you as well? Each item has an `opacity-25` class applied and clicking on images is a no-op. Let me know if this warrants a separate issue and is not related

![Screenshot 2024-07-30 at 23 15 21](https://github.com/user-attachments/assets/1e7268cb-7721-499d-8384-7a7225948566)

**Comment by murisceman** [comment] 2024-07-30 21:27
@andreasvirkus let's track this in https://github.com/pruvious/pruvious/issues/44
